name: CICD

on:
  pull_request:
    branches:
      - "*"

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build for Windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Install 7-Zip
        run: choco install 7zip
      - name: Build binaries for Windows
        run: |
          $env:OUTPUT_DIR = "${{ github.workspace }}\builds"
          mkdir $env:OUTPUT_DIR
          make windows-artifacts PREFIX=$env:OUTPUT_DIR

  build-linux:
    runs-on: ubuntu-22.04
    name: Build for Linux
    env:
      OUTPUT_DIR: ${{ github.workspace }}/builds
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build binaries
        run: |
          PREFIX=${OUTPUT_DIR} make linux-artifacts
      - name: Build wasm image
        run: |
          PREFIX=${OUTPUT_DIR} make c2w-net-proxy.wasm
      - name: sha256sum
        run: |
          ( cd ${OUTPUT_DIR}; sha256sum * ) > "${GITHUB_WORKSPACE}/SHA256SUMS"
          mv "${GITHUB_WORKSPACE}/SHA256SUMS" "${OUTPUT_DIR}/SHA256SUMS"
